<?php
/**
 * Created by PhpStorm.
 * User: jiangheng
 * Date: 19-6-24
 * Time: 上午10:23
 */

namespace JackDou\Swoole\Tests;

use JackDou\Swoole\Services\SwooleEventService;
use Swoole\Server;

class testEvent extends SwooleEventService
{
    public function onManagerStart(Server $server)
    {
        echo "this is testEvent" . PHP_EOL;
        parent::onManagerStart($server); // TODO: Change the autogenerated stub
    }
}
